services:
  - type: web
    name: nailgloss-bhairavi
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_GEMINI_API_KEY
        sync: false
